### ISSUE TITLE
epc options

### ISSUE THREAD

**Issue by kkkclearlove** [qian18long/epciclr2020#4]
hello，I read your paper and I want to rerun your code.But I found a lot of problems,lots of these showed that it caused by the epc parameters.The "--num-stages","--stage-num-episodes" and "--stage-n-envs" lacked the default value.Or maybe the problem is not about it.I put the picture of my problem and thankfully wait your reply.
![image](https://user-images.githubusercontent.com/53371078/84155196-a64d7100-aa9a-11ea-9bb9-806bb3a85c08.png)
![image](https://user-images.githubusercontent.com/53371078/84155188-a3528080-aa9a-11ea-868d-a96982c8fce2.png)

**Comment by kkkclearlove** [comment]
hello,I tried to add your paper's parameters in these epc options.And it make sense.But I also met this problem and I don't know how to solve it.I am looking forward to you see this issue and reply me for this question.
train_helpers.py line 906
    agents[i].start()
TypeError: cannot serialize '_io.BufferedReader' object

**Comment by footoredo** [comment]
Sorry for the late reply. It seems that you do not have the [cloudpickle](https://pypi.org/project/cloudpickle/) package installed. You can compare your package list to the `requirements.txt` in our repo. We've also updated the installation instructions in `README.md`. You can also try to follow that and see if it solves your problem.

**Comment by kkkclearlove** [comment]
> 这么晚才回复很抱歉。似乎您没有安装[cloudpickle](https://pypi.org/project/cloudpickle/)软件包。您可以将您的包裹清单与`requirements.txt`我们的仓库中的包裹清单进行比较。我们还更新了中的安装说明`README.md`。您也可以尝试遵循该步骤，看看它是否可以解决您的问题。

I checked my package and I already install the cloudpickle.Moreover,I searched via the internet and found that maybe this problem is caused by the difference between linux and windows.Because the windows lacked the support of folk,which is supported in linux.I try to change the system of my environment and hope the code will make sense.

**Comment by MaxBleggi** [comment]
The problem is with how you run it I think. I faced a similar issue. Try running it from the train_epc shell file instead of the python file. The reason for this is that there are specific arguments set in the shell file. You can copy these and run through the command line. Pay particular attention to the arguments that use an array like stage-num-episodes
